const STANDARD_SUBSCRIPTION_EXPECTED_OPTIONS = [
    'group_id',
    'frequency_num',
    'frequency_type',
    'frequency_type_text',
];
const STANDARD_SUBSCRIPTION_CHECKOUT_EXPECTED_OPTIONS = [
    'group_id',
    'frequency_num',
    'frequency_type',
    'frequency_type_text',
    'quantities[]',
    'variant_id[]',
    'product_id[]',
];
const LIMITED_LENGTH_SUBSCRIPTION_EXPECTED_OPTIONS = [
    ...STANDARD_SUBSCRIPTION_EXPECTED_OPTIONS,
    'total_recurrences',
];
const LIMITED_LENGTH_SUBSCRIPTION_CHECKOUT_EXPECTED_OPTIONS = [
    ...STANDARD_SUBSCRIPTION_CHECKOUT_EXPECTED_OPTIONS,
    'total_recurrences',
];
const PREPAID_SUBSCRIPTION_EXPECTED_OPTIONS = [
    ...LIMITED_LENGTH_SUBSCRIPTION_EXPECTED_OPTIONS,
    'is_prepaid',
    'prepaid_length_id',
];
const PREPAID_SUBSCRIPTION_CHECKOUT_EXPECTED_OPTIONS = [
    ...LIMITED_LENGTH_SUBSCRIPTION_CHECKOUT_EXPECTED_OPTIONS,
    'is_prepaid',
    'prepaid_length_id',
];

export {
    STANDARD_SUBSCRIPTION_EXPECTED_OPTIONS,
    STANDARD_SUBSCRIPTION_CHECKOUT_EXPECTED_OPTIONS,
    LIMITED_LENGTH_SUBSCRIPTION_EXPECTED_OPTIONS,
    LIMITED_LENGTH_SUBSCRIPTION_CHECKOUT_EXPECTED_OPTIONS,
    PREPAID_SUBSCRIPTION_EXPECTED_OPTIONS,
    PREPAID_SUBSCRIPTION_CHECKOUT_EXPECTED_OPTIONS,
};
