const APPLICATION_UUID = 'b065901c-bf09-11e7-b98f-42010afe0607';
const STANDARD_SUBSCRIPTION_EXPECTED_OPTIONS = [
    'group_id',
    'frequency_num',
    'frequency_type',
    'frequency_type_text',
];
const STANDARD_SUBSCRIPTION_CHECKOUT_EXPECTED_OPTIONS = [
    'group_id',
    'frequency_num',
    'frequency_type',
    'frequency_type_text',
    'quantities[]',
    'variant_id[]',
    'product_id[]',
];
const LIMITED_LENGTH_SUBSCRIPTION_EXPECTED_OPTIONS = [
    ...STANDARD_SUBSCRIPTION_EXPECTED_OPTIONS,
    'total_recurrences',
];
const LIMITED_LENGTH_SUBSCRIPTION_CHECKOUT_EXPECTED_OPTIONS = [
    ...STANDARD_SUBSCRIPTION_CHECKOUT_EXPECTED_OPTIONS,
    'total_recurrences',
];
const PREPAID_SUBSCRIPTION_EXPECTED_OPTIONS = [
    ...LIMITED_LENGTH_SUBSCRIPTION_EXPECTED_OPTIONS,
    'is_prepaid',
    'prepaid_length_id',
];
const PREPAID_SUBSCRIPTION_CHECKOUT_EXPECTED_OPTIONS = [
    ...LIMITED_LENGTH_SUBSCRIPTION_CHECKOUT_EXPECTED_OPTIONS,
    'is_prepaid',
    'prepaid_length_id',
];
const RECURRING_CART_CHECKOUT_EXPECTED_OPTIONS = [
    'frequency_num',
    'frequency_type',
    'frequency_type_text',
];
const RECURRING_CART_CHECKOUT_CASHIER_EXPECTED_OPTIONS = [
    `frequency_num`,
    `frequency_type`,
    `frequency_type_text`,
];
const RECURRING_CART_CHECKOUT_CASHIER_OPTIONAL_PARAMS = [
    'billing_plan',
];

export {
    APPLICATION_UUID,
    STANDARD_SUBSCRIPTION_EXPECTED_OPTIONS,
    STANDARD_SUBSCRIPTION_CHECKOUT_EXPECTED_OPTIONS,
    LIMITED_LENGTH_SUBSCRIPTION_EXPECTED_OPTIONS,
    LIMITED_LENGTH_SUBSCRIPTION_CHECKOUT_EXPECTED_OPTIONS,
    PREPAID_SUBSCRIPTION_EXPECTED_OPTIONS,
    PREPAID_SUBSCRIPTION_CHECKOUT_EXPECTED_OPTIONS,
    RECURRING_CART_CHECKOUT_EXPECTED_OPTIONS,
    RECURRING_CART_CHECKOUT_CASHIER_EXPECTED_OPTIONS,
    RECURRING_CART_CHECKOUT_CASHIER_OPTIONAL_PARAMS,
};
